on:
  push:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: yarn start

    - name: Run
      run: yarn ios